// Foil observability — generated by @getfoil/foil-js wizard
'use strict';

const { Foil } = require('@getfoil/foil-js');

const customerService55 = new Foil({
  apiKey: process.env.FOIL_API_KEY,
  agentName: 'customer_service55',
});

customerService55.ensureAgent({ name: 'customer_service55' });

process.on('SIGTERM', async () => { await customerService55.shutdown(); process.exit(0); });
process.on('SIGINT', async () => { await customerService55.shutdown(); process.exit(0); });

module.exports = { customerService55 };
