// Foil observability — generated by @getfoil/foil-js wizard
'use strict';

const { Foil } = require('@getfoil/foil-js');

// instrumentModules is omitted: this agent has a tool-calling loop.
// The entire loop is traced manually via ctx.llmCall() in processMessage.
const foil = new Foil({
  apiKey: process.env.FOIL_API_KEY,
  baseUrl: 'http://localhost:5003/api',
  agentName: 'agents33',
});

process.on('SIGTERM', async () => { await foil.shutdown(); process.exit(0); });
process.on('SIGINT', async () => { await foil.shutdown(); process.exit(0); });

module.exports = { foil };
